export const batchFourGuides = {
  planBeforeRecording: {
    slug: 'how-to-plan-a-video-before-recording',
    title: 'How to Plan a Video Before Recording',
    description: 'Plan a video before recording with a practical workflow for the goal, outline, script, shot list, setup, and final pre-recording check.',
    intro: 'A short plan can save a long recording session. When you decide what the video needs to say, show, and deliver before the camera or microphone is running, you are less likely to forget key shots or rebuild the story during editing.',
    sections: [
      {heading:'Define one viewer and one useful outcome',paragraphs:['Start by naming the person the video is for and the problem it will solve. A broad subject such as “better phone videos” is hard to record. “How a beginner can lock focus on an iPhone” gives you a clear viewer, action, and result. This approach works for long YouTube tutorials, Shorts, TikToks, Reels, and faceless explainers.','Write one sentence beginning, “By the end, the viewer will…” Use it to remove interesting details that do not serve the main outcome. Those details can become another video. A focused promise also helps you write an accurate title and opening without relying on exaggerated claims.'],example:'For a video about desk lighting, the outcome might be: “By the end, a creator filming at night will know where to place one lamp to reduce hard shadows.”'},
      {heading:'Choose the format and practical limits',paragraphs:['Decide where the video will be published, its approximate length, orientation, and production style. A horizontal YouTube tutorial may need chapters and screen detail. A vertical Reel needs fewer ideas, larger text, and actions that remain visible behind platform controls. A faceless video needs a source for every visual, narration line, and sound.','List the limits you already know: available location, people, equipment, permissions, deadline, and editing time. Design around them. A simple demonstration you can record clearly is usually more useful than an ambitious concept that depends on footage or access you do not have.'],links:[{label:'Estimate a suitable script length',href:'/tools/youtube-script-length-calculator'}]},
      {heading:'Build an outline before a full script',paragraphs:['Arrange the video into a small sequence: hook, essential context, main steps or story beats, proof, summary, and next step. Give each beat a job. For short-form content, the same structure may fit into four lines: problem, action, demonstration, result.','Test the order by explaining it aloud from the outline. If you need to keep jumping backwards, rearrange the beats. Put information just before the viewer needs it. For tutorials, show each action in order. For stories, make the question and change easy to follow.'],example:'A five-minute tutorial outline could be: show the finished result; name the three materials; demonstrate setup; explain one common mistake; compare before and after; recap the settings.',links:[{label:'Check the opening line before recording',href:'/tools/video-hook-checker'},{label:'Learn how to write a relevant video hook',href:'/guides/how-to-write-a-video-hook'}]},
      {heading:'Turn the outline into words and visuals',paragraphs:['Choose a full script when wording, timing, facts, or voiceover coordination matter. Use detailed bullet points for a conversational demonstration where the presenter needs room to react. In either case, read the plan aloud and replace formal phrases with simple spoken language.','Add a visual note beside every important point. Mark talking-head sections, screen recordings, close-ups, B-roll, graphics, captions, and moments where the viewer needs time to look. For faceless channels, this two-column plan prevents the narration from becoming a list of claims supported by unrelated stock footage.'],list:['Spoken line or talking point','Required shot or screen','On-screen text','Source, prop, or asset needed','Audio or transition note']},
      {heading:'Prepare a recording checklist',paragraphs:['Gather props, charge batteries, clear storage, silence notifications, clean the lens, and check the background. Confirm permissions for locations, people, music, images, and third-party clips. Put scripts and shot lists where you can read them without blocking the recording setup.','Record a short test and review the actual file with headphones. Check framing, focus, exposure, microphone noise, screen readability, and caption-safe space. A visible audio meter does not prove that the sound is clean. Fixing a hum or hidden notification now is easier than discovering it after the full take.']},
      {heading:'Record for the edit you planned',paragraphs:['Capture the main delivery in manageable sections and leave a brief pause between takes. Tick off each required shot, then record room tone, cutaways, close-ups, and a few seconds before and after each action. Do not rely on remembering missing footage later.','Before packing away, compare the files with the promise, outline, and shot list. Confirm that the result is visible and the key explanation is complete. Back up irreplaceable footage. The plan is allowed to change during recording, but note the change so the edit follows the version you actually captured.']}
    ],
    cta:{heading:'Check your opening before the first take',text:'Review the length, wording, and speaking time of the hook you plan to record.',label:'Use the Video Hook Checker',href:'/tools/video-hook-checker'},
    faqs:[['Do I need to script every video?','No. Use a full script when exact wording or timing matters, and structured bullet points when a natural demonstration or conversation is more important.'],['How detailed should a shot list be?','Include every shot needed to explain or prove the main points, plus practical details such as location, orientation, props, and audio.'],['Should I plan Shorts differently from YouTube videos?','Yes. Keep a Short to one focused outcome, plan for a vertical frame, and make each visual and sentence useful at a faster pace.'],['How can I plan a faceless video before recording?','Pair every narration beat with a specific visual and record where that asset will come from, including its licence or source when relevant.']]
  },
  simpleWorkflow: {
    slug:'how-to-create-a-simple-content-workflow',title:'How to Create a Simple Content Workflow for YouTube, TikTok, and Reels',
    description:'Create a simple content workflow for YouTube, TikTok, and Reels, from collecting ideas and production to review, scheduling, and reuse.',
    intro:'A content workflow is the path an idea follows until it is published and reviewed. A simple one makes the next action visible, reduces lost files, and helps you plan across YouTube, TikTok, Shorts, and Reels without turning content creation into administration.',
    sections:[
      {heading:'Map how content is made now',paragraphs:['Write down what really happens from idea to publication. Include research, outline, script, recording, editing, captions, thumbnail, description, review, scheduling, and follow-up. Note where work waits, gets repeated, or disappears. Your first workflow should solve those problems rather than copy a complex system made for a large team.','Separate the stages that every post needs from stages used only for certain formats. A YouTube tutorial may need a thumbnail and chapters; a Reel may need a cover and vertical caption check. One shared workflow can contain format-specific checklists without pretending every asset is identical.']},
      {heading:'Use a few clear stages',paragraphs:['Choose stage names that describe the state of the work. A useful starting set is ideas, selected, making, review, scheduled, and published. If “making” hides too much work, split it into scripting, recording, and editing. Each piece of content should have one current stage and one person responsible for moving it.','Define what must be true before an item moves forward. “Ready to record” could mean the outline is approved, facts are checked, props are available, and the shot list is complete. These small definitions stop unfinished work from being passed to the next stage.'],list:['Ideas: worth considering, but not yet promised','Selected: has a clear audience, outcome, format, and owner','Making: script and assets are being produced','Review: content, rights, captions, and export are checked','Scheduled: final file and publishing details are ready','Published: live link and useful notes are recorded']},
      {heading:'Keep one useful record for each piece',paragraphs:['Track only information that helps someone act: working title, audience, platform, format, pillar, owner, status, due date, publish date, and links to files. Add the hook, CTA, or source video when those fields support your decisions. Remove fields that stay empty or are copied without being used.','Use consistent file names and keep the brief, source notes, script, raw media, edit, thumbnail, caption, and export together. For a faceless channel, include asset licences and credits. A link from the calendar to the project folder prevents searches across messages and devices.'],links:[{label:'Organise the workflow in a content calendar',href:'/tools/content-calendar-planner'}]},
      {heading:'Plan by capacity, then batch compatible work',paragraphs:['Estimate the time for the complete process, not only recording. Choose a publishing rhythm that leaves room for corrections and unexpected work. A weekly long video plus three short posts may sound simple, but it is not sustainable if the editing requires more hours than you have.','Batch tasks that share a setup: research related topics, write several hooks, record videos using the same background, or prepare captions in one session. Keep a separate review for every post so batching does not spread one factual, audio, or formatting mistake across the whole group.'],example:'Monday selects two ideas. Tuesday outlines both. Wednesday records the YouTube lesson and two original vertical examples. Thursday edits. Friday checks captions, descriptions, rights, and schedules the finished pieces.',links:[{label:'Build a practical batching session',href:'/guides/how-to-batch-create-content'}]},
      {heading:'Add a short publishing checklist',paragraphs:['Before scheduling, check the first frame, title or cover, audio, captions, crop, links, credits, disclosures, and platform settings. View vertical exports on a phone and long-form exports at several points from start to finish. Confirm that the published promise matches what the content delivers.','Write platform-specific captions and descriptions instead of pasting one block everywhere. Keep the core message consistent, but adapt length, links, hashtags, and calls to action to the platform and the job of the post.'],links:[{label:'Check a finished caption',href:'/tools/caption-character-counter'},{label:'Review a YouTube description',href:'/tools/youtube-description-length-checker'}]},
      {heading:'Review the workflow, not only the numbers',paragraphs:['Once a week, look for blocked items and decide whether to continue, simplify, reschedule, or remove them. Once a month, compare estimated time with actual time and find the stage creating the most rework. Change one part of the system and observe the effect.','Performance data can inform topics and formats, but it cannot guarantee the next result. Also track whether the process was completed, whether the information stayed accurate, and whether the workload was manageable. A good workflow helps you make useful content reliably; it does not promise reach or growth.']}
    ],cta:{heading:'Put your stages on one calendar',text:'Organise ideas, platforms, dates, and production status in a simple browser-based planner.',label:'Use the Content Calendar Planner',href:'/tools/content-calendar-planner'},
    faqs:[['What is a content workflow?','It is the repeatable sequence that moves an idea through planning, production, review, publishing, and learning.'],['Can one workflow cover YouTube, TikTok, and Reels?','Yes. Share the main stages and use small format-specific checklists for details such as thumbnails, vertical crops, captions, and descriptions.'],['How many workflow stages should I use?','Use the fewest stages that still make the next action clear. Many solo creators can begin with five or six.'],['What tool should a beginner use?','A simple calendar, spreadsheet, or board is enough. Choose one place the creator or team will actually keep updated.']]
  },
  hooksCaptionsHashtags: {
    slug:'how-to-use-hooks-captions-and-hashtags-together',title:'How to Use Hooks, Captions, and Hashtags Together',
    description:'Learn how hooks, captions, and hashtags work together on YouTube Shorts, TikTok, and Reels, with clear examples and a practical publishing workflow.',
    intro:'Hooks, captions, and hashtags have different jobs. The hook earns attention inside the video, the caption adds useful context around it, and hashtags label relevant subjects. They work best when all three express the same clear idea without repeating empty hype.',
    sections:[
      {heading:'Give each element one clear job',paragraphs:['The video hook is the opening image, spoken line, or on-screen text that helps the intended viewer understand why the post matters. The caption can summarise the value, add context, credit a source, or provide a next step. Hashtags identify a small number of genuinely relevant topics. None of these elements can rescue a video that does not deliver its promise.','Start with the content outcome, not a list of trending words. Complete this sentence: “This post helps [viewer] do or understand [specific thing].” Use the answer to keep the hook, body, caption, and topic labels aligned.']},
      {heading:'Write the hook from the real payoff',paragraphs:['Choose the most useful or visible result in the video and make it clear early. A direct promise, relevant question, demonstration, or specific mistake can work. Avoid vague openings such as “Wait for it” when you can name the reason to watch. Curiosity should lead to a genuine answer.','Match the first visual to the words. If the hook promises a cleaner edit, show the before-and-after timeline or clip. For faceless content, plan the opening graphic or B-roll beside the narration. Test several lines, read them aloud, and keep the one the video can fully support.'],example:'Hook: “This one timeline marker stops me losing the best moments in a long interview.” The opening screen shows the marker being added, so the claim and proof begin together.',links:[{label:'Write a clear video opening',href:'/guides/how-to-write-a-video-hook'},{label:'Check hook length and speaking time',href:'/tools/video-hook-checker'}]},
      {heading:'Use the caption to add, not duplicate',paragraphs:['A useful caption can name the main takeaway in different words, explain a limitation, list a short step, credit a collaborator, disclose a relationship, or point to a relevant full guide. Put the most important context early because interfaces may shorten the visible preview.','Do not paste the complete spoken script into the post caption unless accessibility or the format specifically calls for it. On-screen captions and subtitles should accurately represent the speech; the post caption has a different job. Keep calls to action proportionate and choose one natural next step.'],example:'Video hook: “Three shots to record before you pack away your product setup.” Post caption: “Save a clean wide shot, a hands-only detail, and five seconds of room tone. They give the edit options when the main take needs a cut.”',links:[{label:'Review caption length and readability',href:'/tools/caption-character-counter'}]},
      {heading:'Choose a small set of relevant hashtags',paragraphs:['Use hashtags that accurately describe the subject, format, audience, or series. Combine a broader category with more specific labels only when each one fits. A phone-lighting tutorial might use a creator-lighting topic and a phone-video topic; unrelated popular tags make the post harder to understand and may conflict with platform guidance.','Check spelling, duplicates, and local meanings. Follow the current rules of each platform because limits and discovery features can change. Hashtags are context signals, not a guarantee of distribution, ranking, views, or growth.'],links:[{label:'Clean and count a hashtag set',href:'/tools/hashtag-counter'}]},
      {heading:'Build all three from one message',paragraphs:['Draft the video first, then write three hook options. Choose the clearest line and write a caption that supplies the most useful missing context. Finally, select only hashtags that describe the finished post. Reading the package together reveals contradictions and unnecessary repetition.','Keep a small message sheet with the audience, core outcome, proof, hook, caption purpose, and topic labels. This is especially useful when one long YouTube video becomes several Shorts, TikToks, or Reels. Each short needs its own focused package rather than the long video title copied everywhere.'],list:['Audience: beginner podcasters','Outcome: remove a steady background hum before recording','Hook: show the noise meter and name the fix','Caption: explain when the fix will not help','Hashtags: audio recording and podcast setup topics']},
      {heading:'Check the complete post before publishing',paragraphs:['Watch once without sound and once with headphones. Confirm that the first frame is readable, subtitles are accurate, the caption does not hide a required disclosure, links work where supported, and hashtags contain no accidental words. Check text against the platform interface safe areas.','After publishing, review several posts together. Look at whether the right subject was clear and whether viewers asked questions that reveal missing context. Improve the message and content, not simply the number of hashtags. Different platforms and audiences respond differently, so treat results as information rather than a promise.']}
    ],cta:{heading:'Review the complete caption package',text:'Check caption length and reading time, then review your hashtags with the dedicated counter.',label:'Use the Caption Character Counter',href:'/tools/caption-character-counter'},
    faqs:[['Should the hook and caption say the same thing?','They should support the same promise, but the caption should add useful context rather than repeat the opening word for word.'],['How many hashtags should I use?','Use only a small, relevant set that fits the finished post and the platform’s current guidance. More is not automatically better.'],['Are on-screen captions the same as a post caption?','No. On-screen captions or subtitles represent spoken content in the video. The post caption sits around the video and can add context or a next step.'],['Can hashtags guarantee more views?','No. Hashtags can help label a topic, but distribution and results depend on many factors and are never guaranteed.']]
  },
  youtubeSeries: {
    slug:'how-to-plan-a-youtube-video-series',title:'How to Plan a YouTube Video Series',
    description:'Plan a useful YouTube video series with a clear audience promise, episode map, production system, internal links, and realistic publishing schedule.',
    intro:'A YouTube series turns a connected subject into several complete videos. The best series gives each episode a useful standalone promise while making the next lesson easy to find. Planning the full path first helps you avoid repeated points, missing steps, and an unrealistic production commitment.',
    sections:[
      {heading:'Choose a subject that deserves several episodes',paragraphs:['A good series has one audience, one broad outcome, and several distinct questions. “Start a home podcast” could support episodes on room choice, microphone position, recording software, editing, and publishing. “My favourite microphone colour” probably does not need a series.','Check that you can offer original examples, reliable sources, and suitable visuals for every proposed episode. For a faceless series, confirm that the screen recordings, diagrams, demonstrations, or licensed assets are practical to produce. Do not stretch one useful idea into repeated videos simply to increase the episode count.']},
      {heading:'Write the series promise and boundaries',paragraphs:['Describe what the viewer will be able to do or understand after completing the series. Define the starting level, what is included, and what is outside the scope. Clear boundaries keep the sequence coherent and help viewers decide whether it is for them.','Choose whether the series is sequential, where each lesson depends on the last, or modular, where episodes can be watched in any order. A sequential course needs stronger recaps and next-episode links. A modular interview or case-study series needs a consistent format and clear individual titles.'],example:'Promise: “A five-part beginner series that takes a creator from an untreated room to a clean first voice recording using equipment they already own.”'},
      {heading:'Map episodes around viewer questions',paragraphs:['List the questions a beginner asks from first decision to finished outcome. Group related questions and give each episode one main result. Put prerequisites early and advanced choices later. Then remove overlap: background information should live in the episode where it becomes useful.','Create a table with the working title, viewer question, takeaway, proof or demonstration, required assets, and connection to the next episode. Keep an extra ideas list outside the committed series so new thoughts do not keep changing the plan.'],list:['Episode 1: choose and test the room','Episode 2: position the microphone','Episode 3: set recording levels','Episode 4: remove simple mistakes in the edit','Episode 5: export and check the final audio']},
      {heading:'Make every episode work on its own',paragraphs:['Viewers may discover episode four first. Open with its specific value, give only the context needed, and deliver a complete result. Briefly point to an earlier episode when it is genuinely required. Avoid long identical introductions that delay the new lesson.','Use honest, descriptive titles and thumbnails that distinguish the episodes. A series name can appear consistently, but lead with the episode’s useful topic. Put the playlist and relevant previous or next episode in the description, cards, end screen, and pinned comment where appropriate.'],links:[{label:'Check a YouTube description before publishing',href:'/tools/youtube-description-length-checker'}]},
      {heading:'Plan production across the whole series',paragraphs:['Outline every episode before fully scripting the first. This exposes repeated sections and shared assets. Estimate research, recording, editing, graphics, thumbnails, and review time. Decide whether to finish several episodes before launch so one delay does not break the sequence.','Batch repeatable work such as studio setup, B-roll, thumbnails, or voiceovers, but review each episode separately. Keep visual and audio conventions consistent without making every opening identical. A simple project template and naming system make shared assets easier to find.'],links:[{label:'Batch related production tasks',href:'/guides/how-to-batch-create-content'},{label:'Estimate script timing for each episode',href:'/tools/youtube-script-length-calculator'}]},
      {heading:'Publish, connect, and improve the plan',paragraphs:['Choose a schedule you can maintain and state it only when you are confident. Create the playlist before or when the first episode is live, order it correctly, and update all links as episodes publish. Use the content calendar to track scripts, shared shots, thumbnails, release dates, and links.','Review audience questions and retention patterns across several episodes. Clarify future lessons or add a bonus episode when it genuinely fills a gap. Do not rewrite the whole series around one result, and do not promise that a series will guarantee views, watch time, ranking, revenue, or channel growth.'],links:[{label:'Schedule the series production and releases',href:'/tools/content-calendar-planner'}]}
    ],cta:{heading:'Map every episode and deadline',text:'Put the series topics, production stages, and planned release dates into one clear calendar.',label:'Use the Content Calendar Planner',href:'/tools/content-calendar-planner'},
    faqs:[['How many videos should be in a YouTube series?','Use the number of distinct episodes needed to deliver the series promise. A focused series may need three to six; a larger subject may need more.'],['Should viewers have to watch the series in order?','Only when later episodes depend on earlier skills. Even then, make each video understandable and useful for viewers who arrive in the middle.'],['Should I record the whole series before publishing?','A buffer can protect the schedule and improve consistency, but the right choice depends on production time and whether the subject may change.'],['How do I link YouTube series episodes?','Use a playlist plus relevant description links, cards, end screens, and pinned comments, and keep those links updated as episodes go live.']]
  },
  longToShorts: {
    slug:'how-to-repurpose-long-videos-into-shorts',title:'How to Repurpose Long Videos into Shorts, TikToks, and Reels',
    description:'Repurpose long videos into useful Shorts, TikToks, and Reels by finding standalone moments, rewriting hooks, reframing footage, and adding context.',
    intro:'Repurposing a long video is more than cutting it into smaller files. A useful Short, TikTok, or Reel needs one complete idea, a clear opening, mobile-friendly visuals, and enough context to make sense to someone who has never seen the source video.',
    sections:[
      {heading:'Start with rights and a useful source',paragraphs:['Use footage, music, graphics, and interviews you own or have permission to adapt for each intended platform. Check licences, participant agreements, and disclosure requirements before editing. A clip being present in your long video does not always mean it can be redistributed everywhere.','Choose a source with specific lessons, demonstrations, stories, comparisons, or answers. Mark moments that can produce a complete payoff. A short clip should help or entertain the viewer by itself; “watch the full video for the answer” is not a substitute for value.']},
      {heading:'Find standalone short-form angles',paragraphs:['Review the transcript, edit timeline, comments, and chapters. Look for one clear problem and answer, a visible before-and-after, a surprising but supportable detail, a small story with a change, or one step that solves a narrow task. Give each candidate a one-sentence outcome.','Do not force every minute into a post. Remove candidates that require long setup, repeat another clip, lack visual support, or cannot be represented accurately in a short runtime. One detailed long video may support several distinct pieces; a simple update may support none.'],example:'A 20-minute home-studio tour could produce a microphone-position demonstration, a cable-labelling tip, and a before-and-after sound comparison. Each has a separate viewer problem and payoff.',links:[{label:'Turn one source idea into distinct posts',href:'/guides/how-to-turn-one-video-idea-into-many-posts'}]},
      {heading:'Rebuild the opening for a new viewer',paragraphs:['Long videos often open with context that works for subscribers but feels incomplete in a short feed. Write a new hook that names or shows the short clip’s exact value. Begin near the useful action, then add only the context required to understand it.','Avoid misleading teaser language. If the clip promises a setting, show and explain the setting. You can mention the full video after delivering the short payoff when it offers a genuinely useful next step.'],example:'Long-form transition: “The next thing I changed was the light.” Short-form hook: “Move a desk lamp to this side if glasses are reflecting the bulb.”',links:[{label:'Write and test a short-form hook',href:'/tools/video-hook-checker'}]},
      {heading:'Edit for a vertical phone screen',paragraphs:['Create a 9:16 sequence and reframe every shot deliberately. Keep the speaker, hands, product, or screen action visible. A simple centre crop may remove the demonstration, lower image quality, or leave empty space. Use punch-ins, layouts, original vertical footage, or supporting graphics when they improve understanding.','Add accurate, readable subtitles and keep essential text away from interface controls. Shorten pauses that do not serve the story, but leave enough time to understand diagrams and actions. Balance speech, music, and effects again; audio mixed for a long video may feel different on a phone.']},
      {heading:'Write a platform-ready caption and package',paragraphs:['Give the short a clear title or cover where the platform supports it. Write a caption that adds context, sources, credits, disclosure, or one next step. Choose only relevant hashtags and review current platform requirements. Remove watermarks and interface graphics when you have clean original media and platform rules require it.','The same core edit can sometimes work across Shorts, TikTok, and Reels, but inspect each upload. Preview crops, cover placement, caption length, links, music rights, and safe areas on each platform. Platform features and policies change, so verify important settings at publishing time.'],links:[{label:'Check caption length and reading time',href:'/tools/caption-character-counter'},{label:'Review and clean relevant hashtags',href:'/tools/hashtag-counter'}]},
      {heading:'Create a repeatable repurposing workflow',paragraphs:['During long-form planning, note possible short moments and capture important demonstrations in both orientations when practical. After editing the long video, make a shortlist, choose the strongest distinct angles, write new hooks, create vertical edits, review captions and rights, then schedule them around other content.','Track each short back to its source video and record where it has been published. Space similar clips so the audience is not shown the same lesson repeatedly. Review results by the job of each post, but remember that no editing or distribution method guarantees views, reach, ranking, revenue, or growth.'],links:[{label:'Schedule source videos and derived posts',href:'/tools/content-calendar-planner'},{label:'Plan content for a faceless channel',href:'/guides/how-to-plan-content-for-a-faceless-channel'}]}
    ],cta:{heading:'Plan the repurposed posts',text:'Track the source, platform, format, production status, and publish date for each useful short-form angle.',label:'Use the Content Calendar Planner',href:'/tools/content-calendar-planner'},
    faqs:[['Can I post the same clip on Shorts, TikTok, and Reels?','Often, if you hold the necessary rights, but review each platform’s crop, caption, cover, music, watermark, disclosure, and current rules.'],['How long should a repurposed short video be?','Use the time needed to deliver one complete idea clearly. Do not pad a clip to a target or rush a demonstration to fit an arbitrary length.'],['Should every short link to the full video?','No. First make the short useful on its own. Mention the full video only when it provides a relevant next step.'],['Can I repurpose videos for a faceless channel?','Yes. Rewrite the opening, use purposeful vertical visuals, check asset rights, and make sure the clip remains clear without the long video’s context.']]
  }
};
