const updated = { lastUpdated: 'September 9, 2026', lastUpdatedIso: '2026-09-09' };

export const batchFiveGuides = {
  ideaToUpload: {
    ...updated,
    slug: 'how-to-plan-a-youtube-video-from-idea-to-upload',
    title: 'How to Plan a YouTube Video from Idea to Upload',
    description: 'Plan a YouTube video from the first idea through research, outline, recording, editing, title, description, thumbnail, checks, and upload.',
    intro: 'A YouTube video becomes easier to finish when every stage has a clear decision and a useful handoff to the next. This workflow takes one focused idea from an audience question to a checked upload without treating the plan as a promise of views or growth.',
    sections: [
      {heading:'Turn the idea into one viewer promise',paragraphs:['Start with a real question, problem, comparison, or outcome for a specific viewer. “Camera settings” is only a subject; “camera settings for filming a desk tutorial at night” suggests what to explain, demonstrate, and leave out. Write the intended outcome in one sentence before researching.','Check that the idea can support useful detail, honest evidence, and visuals you can create or legally use. Define the boundary too. A focused video may explain how to choose a microphone position without becoming a complete guide to acoustics, editing, and podcast distribution.'],example:'Viewer: a beginner recording voiceovers in a bedroom. Promise: “By the end, you will be able to choose and test one microphone position using equipment you already have.”',links:[{label:'Shape the idea into a practical outline',href:'/tools/video-script-outline-builder'}]},
      {heading:'Research the answer and plan the proof',paragraphs:['Collect only the information needed to support the promise. Prefer current primary sources for changing platform features, product details, policies, or technical claims. Record source names and links while researching so credits and fact checks do not become a last-minute search. Separate facts from your own experience and label uncertainty honestly.','Decide what the viewer needs to see, not only what you want to say. List demonstrations, screen recordings, comparisons, diagrams, examples, and B-roll beside the relevant point. Confirm permissions for music, footage, images, fonts, and contributions before production.'],list:['Core question and intended viewer','Three to five main teaching or story beats','Source or evidence for factual claims','Visual proof for each important beat','Rights, credits, and disclosure requirements']},
      {heading:'Outline, script, and time the video',paragraphs:['Arrange the material in the order a new viewer needs it: a clear opening, essential context, the main steps or argument, a useful recap, and one relevant next action. Put the strongest value early. If a section does not advance the promise, move it to another video or remove it.','Choose the right writing depth for the format. A precise tutorial or faceless voiceover may need a full script; a demonstration or interview may work better from detailed beats. Read scripted words aloud and time them with planned visual pauses. This catches repetition and unrealistic pacing before recording.'],example:'An eight-minute tutorial might reserve 20 seconds for the opening, 60 seconds for setup, five minutes for three demonstrated steps, one minute for troubleshooting, and 40 seconds for the recap and next step.',links:[{label:'Estimate a useful script length',href:'/tools/youtube-script-length-calculator'},{label:'Plan the recording before you begin',href:'/guides/how-to-plan-a-video-before-recording'}]},
      {heading:'Prepare and capture the required assets',paragraphs:['Turn the outline into a recording checklist. Prepare the location, camera, microphone, lighting, screen, props, batteries, storage, and file names. Record a short test and check focus, framing, exposure, noise, and screen readability on the device where viewers are likely to watch.','Capture the main performance in manageable sections, then collect the planned demonstrations, cutaways, room tone, clean screenshots, and alternate takes. Mark strong takes as you work. Back up irreplaceable files before editing, and note anything missing while the setup is still available.'],links:[{label:'Build a purposeful supporting shot list',href:'/guides/how-to-plan-b-roll-for-videos'}]},
      {heading:'Edit for clarity, then package honestly',paragraphs:['Build a rough cut around the viewer promise before polishing transitions or effects. Remove repeated explanations, long setup, and visuals that do not help understanding. Check factual accuracy, captions, audio balance, pacing, source credits, and required disclosures. Watch the export once without stopping.','Write the title and thumbnail as a truthful pair: identify the topic and create a clear reason to choose the video without promising an outcome the video cannot deliver. Use the description for a concise summary, chapters when helpful, sources, credits, disclosures, and relevant links. Preview every element on a small screen.'],links:[{label:'Check the YouTube title length',href:'/tools/youtube-title-length-checker'},{label:'Review the description structure',href:'/tools/youtube-description-length-checker'},{label:'Check thumbnail wording',href:'/tools/thumbnail-text-checker'}]},
      {heading:'Complete a calm pre-publish review',paragraphs:['Confirm the final file, title, thumbnail, description, audience setting, visibility, playlist, subtitles, cards, end screen, links, credits, and disclosures. Use YouTube’s current interface and policy guidance at upload time because features and requirements can change. Schedule only after the public-facing page looks right.','After publication, check the page as a viewer and correct obvious link or caption problems. Record useful lessons from audience questions and aggregate performance, but avoid changing the entire process because of one result. No workflow can guarantee views, watch time, rankings, revenue, monetisation, or growth.'],links:[{label:'Run the final publishing checklist',href:'/tools/video-publishing-checklist'}]}
    ],
    cta:{heading:'Take the video through a final check',text:'Review the publishing details, links, accessibility, rights, and packaging before you schedule or publish.',label:'Use the Video Publishing Checklist',href:'/tools/video-publishing-checklist'},
    faqs:[['What should I plan before making a YouTube video?','Define the viewer, outcome, main beats, evidence, visuals, recording needs, packaging, and final checks before production begins.'],['Should I write the title before the script?','A working title can focus the plan, but revise it after editing so it describes the finished video accurately.'],['Do all YouTube videos need a full script?','No. Tutorials, interviews, demonstrations, and commentary may use different levels of scripting. Choose the lightest format that keeps the video accurate and coherent.'],['How long should planning take?','Use enough time to remove uncertainty that would slow production. A simple Short may need minutes; a researched tutorial may need several sessions.']]
  },
  retentionStructure: {
    ...updated,
    slug: 'how-to-improve-video-retention-with-better-structure',
    title: 'How to Improve Video Retention with Better Structure',
    description: 'Improve video structure with a clear promise, purposeful opening, logical content beats, useful pattern changes, and an honest retention review.',
    intro: 'Better structure gives viewers a clear reason to continue from one moment to the next. It cannot guarantee retention, but it can remove confusion, repetition, and delayed value that make an otherwise useful video harder to follow.',
    sections: [
      {heading:'Define the viewing path before the opening',paragraphs:['Write the viewer’s starting point and the useful state they should reach by the end. Then list the few questions they must answer along the way. This creates a viewing path rather than a collection of related tips. A tutorial may move from diagnosis to setup to action to verification; a story may move from goal to obstacle to decision to consequence.','Choose one primary promise. Side topics create extra setup and weaken the connection between sections. When a useful idea does not serve the current path, save it for a follow-up. A narrower promise is often easier to explain clearly and support with relevant visuals.'],example:'For “Fix hollow voiceover audio in a small room,” the path could be: recognise the sound, test a new position, reduce nearby reflections, record again, and compare the result.'},
      {heading:'Open with specific value and immediate evidence',paragraphs:['The opening should quickly establish what the video will help the right viewer do or understand. Show the problem, result, question, or tension when possible. Avoid a long greeting, channel history, or vague teaser before the topic becomes clear.','Match the claim to the finished video. An opening such as “Here is how I organised 40 clips for a five-minute edit” sets a specific expectation; the next shot can show the folder system. Curiosity is useful when the answer is real, relevant, and delivered—not when basic information is deliberately withheld.'],links:[{label:'Draft and review an opening line',href:'/tools/video-hook-checker'},{label:'Learn how to write a supported hook',href:'/guides/how-to-write-a-video-hook'}]},
      {heading:'Build sections around questions and payoffs',paragraphs:['Give every section one job and name it in plain language while outlining. Begin with the question or problem, provide the needed explanation, then show a result, example, or next decision. Place prerequisite information before the step that uses it, and move optional detail later.','Use transitions to explain why the next section matters. “Now that the audio is clean, check whether it remains clear under music” creates a logical bridge. A transition should add orientation, not recap the whole video. Deliver small payoffs throughout instead of saving all useful information for the end.'],list:['State the immediate question','Give only the context needed','Show the action, evidence, or example','Confirm what changed or what to notice','Connect the result to the next beat'],links:[{label:'Map the beats in a reusable outline',href:'/tools/video-script-outline-builder'}]},
      {heading:'Change the presentation when the idea changes',paragraphs:['Visual and audio changes can restore attention when they clarify new information. Move from explanation to demonstration, switch from a wide shot to a relevant close-up, add a readable diagram, or let an example play without narration. Do not add random movement merely to create activity.','Plan the screen as carefully as the words. Keep important text readable, give viewers time to inspect examples, and make captions accurate. For faceless content, avoid using unrelated stock clips as decoration; choose visuals that prove, explain, locate, or reinforce the current point.'],example:'When a tutorial moves from “why the setting matters” to “where to find it,” replace the talking head with a labelled screen recording at the exact moment the action begins.'},
      {heading:'Cut friction in the script and edit',paragraphs:['Read the script aloud and mark repeated premises, throat-clearing phrases, overlong definitions, and examples that prove the same point. In the edit, shorten pauses that feel accidental while preserving time needed to understand an action or emotion. Clear pacing is not the same as speaking as fast as possible.','Ask a fresh reviewer to note where they expected an answer, became confused, or felt a section was complete. Do not explain the video to them first. Their questions reveal missing setup and misleading transitions more reliably than a general request to “make it engaging.”'],links:[{label:'Check narration length and pace',href:'/tools/voiceover-duration-calculator'}]},
      {heading:'Use retention data as a diagnostic clue',paragraphs:['When enough data is available, compare audience-retention patterns with the actual timeline. A drop may relate to a mismatch in the opening, a confusing step, a technical problem, an expected ending, or the audience source. A replayed section may be valuable or simply difficult to understand. The graph does not explain the cause by itself.','Review several comparable videos and combine the data with comments, production notes, and the content’s purpose. Test one meaningful structural change at a time. Results vary across topics and audiences, and no hook, editing rhythm, or outline guarantees retention, distribution, views, or growth.'],links:[{label:'Calculate watch time from real inputs',href:'/tools/watch-time-calculator'}]}
    ],
    cta:{heading:'Outline the viewing path',text:'Turn one viewer promise into a hook, logical content beats, evidence, and a clear next step before recording.',label:'Use the Video Script Outline Builder',href:'/tools/video-script-outline-builder'},
    faqs:[['What does audience retention mean?','It describes how much of a video viewers watch over time. Interpret it with the video timeline, audience source, and other context.'],['Does a fast edit always improve retention?','No. Fast cuts can make a video harder to understand. Change pace and visuals when doing so supports the idea or emotion.'],['Where should the most useful information go?','Start delivering relevant value early, then place later information in the order viewers need it. Do not delay a promised answer only to extend runtime.'],['Can better structure guarantee more watch time?','No. Structure can improve clarity, but results also depend on topic, audience, packaging, execution, distribution, and other factors.']]
  },
  weeklyPlan: {
    ...updated,
    slug: 'how-to-create-a-weekly-content-plan',
    title: 'How to Create a Weekly Content Plan for YouTube, TikTok, and Reels',
    description: 'Create a realistic weekly content plan for YouTube, TikTok, and Instagram Reels using priorities, capacity, production stages, and reusable ideas.',
    intro: 'A weekly content plan connects what you want to publish with the time and energy you actually have. The aim is not to fill every day. It is to choose a useful mix, finish it well, and leave enough room for review and unexpected work.',
    sections: [
      {heading:'Start with capacity, not posting targets',paragraphs:['List the hours and production windows genuinely available this week. Include research, scripting, setup, recording, editing, review, captions, thumbnails, uploading, and administration. Subtract fixed commitments and keep a buffer rather than assigning every free hour.','Estimate formats from your own recent work. A researched YouTube tutorial may take several sessions, while a direct short-form answer may take one. If you are new, make a cautious estimate and update it after the week. A smaller completed plan teaches more than an overloaded calendar.'],example:'A creator with six hours might plan one focused YouTube video and one related vertical clip, not a long video plus daily posts on three platforms.'},
      {heading:'Choose one weekly priority and supporting pieces',paragraphs:['Name the most valuable audience problem or project for the week. Make that the anchor. Supporting posts can answer smaller questions, demonstrate one step, share a useful example, or direct interested viewers to a deeper resource after delivering their own value.','Do not automatically copy one post everywhere. YouTube, TikTok, and Reels have different viewing contexts and publishing options. Adapt the opening, framing, caption, cover, length, rights, and next step for each destination, and check current platform requirements when publishing.'],links:[{label:'Adapt one useful idea across formats',href:'/guides/how-to-turn-one-video-idea-into-many-posts'}]},
      {heading:'Map outcomes before formats',paragraphs:['For each planned item, write the audience, single outcome, format, platform, and evidence or visual needed. Then give it a working title. This prevents vague entries such as “post Reel” that still require every creative decision on production day.','Balance dependable formats with one controlled experiment if capacity allows. A dependable post uses a process you understand; an experiment tests one new topic, presentation, or workflow choice. Avoid changing subject, hook style, length, and editing approach all at once because the result will be difficult to interpret.'],list:['Audience and problem','One useful outcome','Platform and format','Hook or working title','Assets and rights needed','Next production action']},
      {heading:'Schedule production stages before publish dates',paragraphs:['Work backwards from any real deadline. Assign research, outline, script, recording, edit, review, packaging, and upload windows. Group compatible tasks, such as recording two voiceovers in one prepared setup, but give every finished item its own quality check.','Use clear statuses and a single next action. If Tuesday’s entry says only “YouTube video,” the plan is not actionable. “Record sections 1–3 after a 30-second audio test” is. Protect review time; a schedule that ends when the export completes leaves no room to catch errors.'],links:[{label:'Organise dates, formats, and statuses',href:'/tools/content-calendar-planner'},{label:'Batch compatible work without rushing',href:'/guides/how-to-batch-create-content'}]},
      {heading:'Create a practical weekly board',paragraphs:['Keep the board small enough to scan. Each content item should link to its working files and show its current status, next action, and intended publish window. Separate the active week from an idea backlog so uncommitted possibilities do not look like missed deadlines.','A simple rhythm might use Monday for research and outlines, Tuesday for scripts, Wednesday for recording, Thursday for editing, and Friday for review and scheduling. This is only a model. Arrange work around your energy, collaborators, equipment, and the production stages that are hardest to switch between.'],example:'Anchor: Friday YouTube tutorial. Support: Tuesday Reel showing one visual example. Monday research supports both; Wednesday captures horizontal and vertical footage; Thursday edits; Friday reviews and publishes.'},
      {heading:'Close the week with a short review',paragraphs:['Record what shipped, what took longer than expected, what became blocked, and which audience questions deserve follow-up. Reschedule unfinished work only when it is still useful; simplify or remove it otherwise. Carrying every old task forward makes the next plan unrealistic.','Use performance signals over a meaningful period, not as a daily score. Compare similar content and connect observations to decisions you can test. A weekly plan supports consistency and learning, but it cannot guarantee reach, engagement, rankings, revenue, or growth.']}
    ],
    cta:{heading:'Build the week around real capacity',text:'Map each content item by platform, date, format, status, and next production action.',label:'Use the Content Calendar Planner',href:'/tools/content-calendar-planner'},
    faqs:[['How many posts should be in a weekly content plan?','Use the number you can produce and review well with your real capacity. There is no universal posting target.'],['Should I post on YouTube, TikTok, and Reels every week?','Only if each platform serves your audience and the workload is sustainable. It is reasonable to prioritise one platform and adapt selectively.'],['How far ahead should weekly content be planned?','Choose the main topics and deadlines before the week starts, then keep some capacity open for changes, questions, and delays.'],['What should I do with unfinished content?','Decide whether it is still useful, then reschedule it deliberately, simplify it, or remove it. Do not automatically overload the next week.']]
  },
  clearPackaging: {
    ...updated,
    slug: 'how-to-write-clear-video-titles-descriptions-and-captions',
    title: 'How to Write Clear Video Titles, Descriptions, and Captions',
    description: 'Write clear video titles, YouTube descriptions, and social captions that set accurate expectations, add useful context, and work together.',
    intro: 'Titles, descriptions, and captions should make a finished video easier to understand and choose. They have different jobs, but all three should reflect the same honest promise instead of competing with one another or making claims the content cannot support.',
    sections: [
      {heading:'Start with a one-sentence content promise',paragraphs:['Before writing publishing copy, complete this sentence: “This video helps [viewer] do, decide, or understand [specific outcome].” Use the finished edit, not the original idea, as your source. If the video changed during production, the packaging must change too.','List the most concrete topic, method, audience, constraint, or example. These details make copy useful without exaggeration. Avoid claims such as guaranteed views, instant growth, or certain income. If a result came from your own experience, present it as an example rather than a universal outcome.'],example:'Broad subject: desk lighting. Clear promise: “This video shows a beginner how to position one desk lamp for a clearer nighttime talking-head shot.”'},
      {heading:'Write a title that identifies value quickly',paragraphs:['Lead with words that help the intended viewer recognise the topic. Use a clear outcome, question, comparison, process, or constraint. Remove filler that delays the meaning, and keep important wording visible when the title is shortened on smaller screens.','A title and thumbnail should add up to one coherent idea. They can divide the work—the title names the process while the thumbnail shows the visual difference—but should not make conflicting promises. Review spelling, dates, names, and any number stated in the title against the final video.'],list:['How to Light a Desk Video with One Lamp','USB vs XLR Microphones for a First Home Setup','I Organised 40 B-Roll Clips with This Folder System','Three Checks Before You Export a YouTube Tutorial'],links:[{label:'Review title length and readability',href:'/tools/youtube-title-length-checker'},{label:'Check short thumbnail wording',href:'/tools/thumbnail-text-checker'}]},
      {heading:'Use the YouTube description as a useful reference',paragraphs:['Open with a concise summary that confirms what the video covers. Then add chapters when they improve navigation, followed by relevant resources, sources, credits, disclosures, and a focused next step. Put essential context before optional channel boilerplate.','Label links so viewers know where they lead. Check affiliate, sponsorship, safety, and other disclosure requirements that apply to your content and region. Do not paste unrelated keywords or repeat the title in several forms. A readable description serves people first.'],example:'Opening: “This tutorial compares two microphone positions in the same untreated room, then shows how to run a short recording test before choosing one.”',links:[{label:'Check description length and structure',href:'/tools/youtube-description-length-checker'},{label:'Plan chapters, sources, and disclosures',href:'/guides/how-to-write-better-video-descriptions'}]},
      {heading:'Write social captions that add context',paragraphs:['A TikTok, Reel, or Short caption can supply a missing step, limitation, source, credit, disclosure, or simple next action. It does not need to transcribe the entire video. Put the most important context early because apps may shorten the preview.','Match the tone to the content and use line breaks only when they improve scanning. If you ask for a comment, save, or click, make the request relevant and proportionate. Choose a small set of accurate hashtags only when useful, and check each platform’s current features and limits at publishing time.'],example:'Video: a 20-second cable-labelling demonstration. Caption: “Label both ends before the cable goes behind the desk. I use the same short code on the cable and the audio-interface input.”',links:[{label:'Review caption length and reading time',href:'/tools/caption-character-counter'},{label:'Count and clean relevant hashtags',href:'/tools/hashtag-counter'}]},
      {heading:'Edit the complete package together',paragraphs:['Place the final frame, title, thumbnail or cover, description, and caption side by side. Check that a new viewer would form the right expectation, that each element adds something useful, and that terminology stays consistent. Remove repeated phrases that make the package feel mechanical.','Read the copy aloud and preview it on a phone. Look for truncated meaning, ambiguous pronouns, dense blocks, accidental hashtags, broken links, unsupported superlatives, and accessibility problems. Ask a reviewer what they expect the video to contain before they watch it.'],links:[{label:'Understand how hooks, captions, and hashtags connect',href:'/guides/how-to-use-hooks-captions-and-hashtags-together'}]},
      {heading:'Learn from results without chasing guarantees',paragraphs:['After publishing, note whether audience questions reveal unclear packaging or missing context. Compare similar videos over time rather than rewriting titles repeatedly after every small change. If you revise copy, keep a record of what changed and why.','Clear packaging can help the right viewer understand the content, but it cannot guarantee clicks, retention, reach, search ranking, revenue, monetisation, or growth. The video, audience, platform, timing, competition, and many other factors influence results.']}
    ],
    cta:{heading:'Check the title before publishing',text:'Review character count, words, readability, and the opening wording of your finished YouTube title.',label:'Use the YouTube Title Length Checker',href:'/tools/youtube-title-length-checker'},
    faqs:[['What is the difference between a description and a caption?','A YouTube description can act as a detailed reference below a video. A social caption is usually shorter and adds context around a feed post.'],['Should the title and thumbnail use the same words?','Not necessarily. They should communicate one accurate idea, but each can contribute different useful information.'],['Should I put hashtags in every caption?','No. Use a small, relevant set only when it helps label the content and fits current platform guidance.'],['Can a better title guarantee more views?','No. A clear title can set expectations, but outcomes depend on the content, audience, platform, competition, and other factors.']]
  },
  facelessEditPrep: {
    ...updated,
    slug: 'how-to-prepare-a-faceless-video-before-editing',
    title: 'How to Prepare a Faceless Video Before Editing',
    description: 'Prepare a faceless video for editing by locking the story, cleaning narration, mapping visuals, checking rights, and organising project files.',
    intro: 'A faceless edit becomes much easier when the story, voiceover, visuals, and rights are organised before the timeline fills up. Preparation reduces searching and rework while helping every visual support what the viewer is hearing.',
    sections: [
      {heading:'Lock the purpose and structure first',paragraphs:['Write the intended viewer, video promise, and final section order at the top of the project brief. Confirm that the script delivers the promise without repeated background or unsupported claims. Structural changes are cheaper in a document than after music, captions, and animation have been timed.','Break the script into labelled beats and give every beat a job: establish the problem, explain a cause, demonstrate a step, compare options, or confirm a result. Mark statements that need a citation, screenshot, diagram, or other evidence.'],links:[{label:'Plan a faceless video from the beginning',href:'/guides/how-to-plan-a-faceless-youtube-video'},{label:'Create a structured script outline',href:'/tools/video-script-outline-builder'}]},
      {heading:'Record and clean the master narration',paragraphs:['Record a short test in the intended position and listen with headphones before completing the session. Check background noise, reflections, clipping, plosives, pacing, and pronunciation. Keep the microphone position and recording settings consistent, and capture room tone for natural edits.','Edit obvious mistakes, duplicate takes, and distracting noise before building detailed visuals. Do not process the voice so aggressively that it sounds brittle or unnatural. Export or consolidate a clearly named master narration and keep the untouched recording. If timing changes later, update the visual map instead of silently speeding speech beyond a comfortable pace.'],links:[{label:'Estimate and review voiceover duration',href:'/tools/voiceover-duration-calculator'},{label:'Plan comfortable narration pacing',href:'/guides/voiceover-pacing-for-videos'}]},
      {heading:'Create a visual map beside the narration',paragraphs:['Divide the narration by sentence or idea and assign a visual purpose to each part. A visual can demonstrate an action, prove a claim, identify a person or place, show a comparison, provide necessary context, or create an intentional pause. Avoid filling every gap with loosely related stock footage.','Use placeholders only when they are specific enough to find or create. “B-roll here” is not actionable; “close-up of labelled input two while the narrator names it” is. Note orientation, approximate duration, crop needs, captions, source, and whether the asset is ready.'],example:'Narration: “The second position reduced desk reflections.” Visual: side-by-side waveform and labelled room diagram, held long enough to compare both positions.',links:[{label:'Turn the script into a B-roll plan',href:'/guides/how-to-plan-b-roll-for-videos'}]},
      {heading:'Verify rights, credits, and accuracy',paragraphs:['For every external image, clip, sound, font, template, or quotation, record its source, licence, permitted use, required credit, and any restrictions. Keep proof of permission with the project. Do not assume that material found through search, social media, or another video is free to reuse.','Check names, dates, quotations, figures, screenshots, and product or platform instructions against reliable current sources. Flag any visual recreation or illustrative footage that could be mistaken for evidence. Prepare disclosures for sponsorships, affiliate relationships, synthetic or altered media, and other requirements that apply.']},
      {heading:'Organise files for fast, safe decisions',paragraphs:['Create a predictable project structure for narration, music, sound effects, original footage, licensed assets, graphics, captions, project files, exports, sources, and licences. Use descriptive file names with a subject, shot, version, and date when useful. Avoid “final-final-2” by using clear version numbers.','Make proxies or optimised copies when the editing system needs them, but preserve the original media. Back up irreplaceable assets in a separate location. Confirm the frame rate, resolution, colour handling, and audio sample rate before building the main sequence so technical conversions do not appear late.'],list:['01_project-brief-and-sources','02_narration-original-and-clean','03_original-video-and-screen-recordings','04_licensed-assets-and-licences','05_graphics-music-and-captions','06_edit-projects-and-exports']},
      {heading:'Run a pre-edit handoff check',paragraphs:['Read the final script while following the visual map. Confirm that every important statement has suitable support, every required asset exists, and the opening has both clear words and a relevant first visual. List deliberate gaps as tasks with an owner or next action.','The package is ready when an editor can understand the audience, promise, section order, narration version, visual choices, sources, rights, technical settings, and delivery requirements without guessing. This preparation supports quality and efficiency, but it does not guarantee views, retention, monetisation, revenue, or growth.'],links:[{label:'Review publishing requirements early',href:'/tools/video-publishing-checklist'}]}
    ],
    cta:{heading:'Prepare the edit from a clear outline',text:'Map the hook, content beats, visual notes, call to action, and supporting details before opening the timeline.',label:'Use the Video Script Outline Builder',href:'/tools/video-script-outline-builder'},
    faqs:[['Should I record the voiceover before editing a faceless video?','Usually, yes. A cleaned narration provides timing and structure, though animation-led or music-led formats may need a different workflow.'],['How detailed should a visual map be?','It should identify what the viewer needs to see, why it is useful, where it comes from, and whether it is ready.'],['Can I use images or clips found online?','Only when you have the rights or permission needed for the intended use and follow any licence, credit, and platform requirements.'],['What files should I give a video editor?','Provide the approved brief, script, narration, visual map, organised assets, sources and rights notes, technical settings, and delivery requirements.']]
  }
};
